#url: https://tianqi.name #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: 아프지 않음
description: > #this means to ignore newlines until "nav_lists:"
    ita9naiwa...
nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /blog/about.html

paths:
  #home: /blog
  #all:  /blog/all.html
  #rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository: ita9naiwa/ita9naiwa.github.io
repository_tree: master

## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Seoul

## Author & social ##
author:
  name: "Hyunsung Lee"
  email: ita9naiwa@gmail.com
  facebook:  mendou12@naver.com
  github:  ita9naiwa
  # linkedin:  #your Linkedin username

## Comment system (Disqus) ##
disqus:
  shortname: ita9naiwa-github-id #the Disqus shortname for the site

## Google Analytics ##
ga_tracking_id: UA-110195370-1 #Google analytics id for the site

## Reading quantity (LeanCloud) ##
leancloud:
  app_id: uAG3OhdcH8H4fxSqXLyBljA7-gzGzoHsz
  app_key: Mzf5m9skSwYVWVXhGiYMNyXs
  app_class: ThomasBlog

mathjax: true

## Paginate ##
paginate: 10
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html # text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
#server_url: "0.0.0.0"

## Development ##
#isdebug: true
